[project]
name = "takt"
version = "0.1.0"
description = ""
authors = [
    {name = "Shamil Abdulaev",email = "ashm.tech@proton.me"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
]

[tool.poetry]
packages = [{include = "takt", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
