"""Names of the metadata keys that have their own field."""

from typing import Final

KNOWN_METADATA_KEYS: Final[tuple[str, ...]] = (
    'name',
    'unit',
    'loops',
    'inner_loops',
    'date',
    'duration',
    'timer',
    'tags',
    'description',
    'calibrate_loops',
    'recalibrate_loops',
    'calibrate_warmups',
    'recalibrate_warmups',
    'python_version',
    'python_implementation',
    'python_executable',
    'python_compiler',
    'python_cflags',
    'python_config_args',
    'python_hash_seed',
    'python_gc',
    'mem_max_rss',
    'command_max_rss',
    'mem_peak_pagefile_usage',
    'cpu_count',
    'cpu_affinity',
    'cpu_config',
    'cpu_freq',
    'cpu_machine',
    'cpu_model_name',
    'cpu_temp',
    'aslr',
    'hostname',
    'platform',
    'boot_time',
    'uptime',
    'load_avg_1min',
    'runnable_threads',
    'perf_version',
    'performance_version',
    'timeit_stmt',
    'timeit_setup',
    'timeit_teardown',
    'timeit_duplicate',
    'commit_id',
    'commit_branch',
    'commit_date',
    'patch_file',
    'hooks',
)
